### ISSUE TITLE
Please can you explain this use of regex

### ISSUE THREAD

**Issue by oliver-foggin** [FeatherweightLabs/FeatherweightRouter#20]
Hey, in your readme you have this...

<img width="297" alt="screen shot 2017-12-05 at 14 30 08" src="https://user-images.githubusercontent.com/26765636/33612240-e41fc118-d9c8-11e7-81e8-a1a45d989569.png">

But I am terrible at regex and have no idea what these are doing?

Also, it is the same regex in both cases. How does this work with your routes as this could mean one route would match in two places?

Thanks

**Comment by wpK** [comment]
They create a [named captured group](https://www.regular-expressions.info/named.html) `(?<name>regex)` which captures a [word character](https://www.regular-expressions.info/shorthand.html) `\w` [one or more times](https://www.regular-expressions.info/repeat.html) `+`.

Both regular expressions are used to as a predicate for matching a child of the parent. They will not both match because the parent paths will never match (animals, zoos).

Examples:

- /animals/dog
- /animals/cat
- /zoos/bronx
